# Wild Willows — Harper application config

rest: true

graphqlSchema:
  files: 'schema.graphql'

jsResource:
  files: 'resources.js'

dataLoader:
  files: 'data/{achievements,animals-1,animals-2,biomes,habitat-objects,recipes,resources,tools}.json'
