// Reading the server as TEXT.
//
// A handful of suites check things no runtime assertion can reach: that every
// refusal carries its message key, that a metric the dashboard renders is
// actually written somewhere, that the rate tier the docs page prints is the
// tier the code enforces. They do it by grepping the server source.
//
// That source used to be one file, so they each did readFileSync('server/resources.ts').
// It is now split across server/*.ts, and a test pinned to the entry file would
// quietly stop seeing almost all of the code while still passing — the worst
// possible failure for a suite whose whole job is to catch omissions. So they go
// through here instead.
//
// ORDER MATTERS. `LAYERS` lists the modules in the same order they appeared in
// the original single file, so a test that asserts one thing appears before
// another still means what it meant. `covers every module` below fails if a new
// server module is added and not listed, which is what stops this file from
// silently going stale.

import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';

// vitest runs from the repo root, same as the other source-scanning suites.
const SERVER = resolve(process.cwd(), 'server');

/** Authored server modules, in dependency order — the order of the old single file. */
export const LAYERS = [
	'core',
	'store',
	'keys',
	'worlds',
	'home',
	'player',
	'metrics',
	'biome',
	'tasks',
	'rate-limit',
	'achievements',
	'endpoints-game',
	'endpoints-metrics',
	'endpoints-admin',
	'endpoints-telemetry',
	'endpoints-pages',
	'resources',
	'weather',
] as const;

/** Build output, not authored source: generated by scripts/, and megabytes of base64. */
export const GENERATED = new Set([
	'pages.ts',
	'img-assets.ts',
	'pdf-assets.ts',
	'theme-audio.ts',
	'page-lastmod.ts',
	// The URL table, generated from scripts/site-pages.mjs.
	'site-pages.ts',
]);

export interface ServerFile {
	/** Repo-relative path, for error messages that a human can act on. */
	path: string;
	src: string;
}

/** Every authored server module, in layer order. */
export function serverFiles(): ServerFile[] {
	return LAYERS.map((name) => ({
		path: `server/${name}.ts`,
		src: readFileSync(resolve(SERVER, `${name}.ts`), 'utf8'),
	}));
}

/** All of the above joined, for the many checks that only need "does this appear". */
export function serverSource(): string {
	return serverFiles()
		.map((f) => f.src)
		.join('\n');
}

/** The module names on disk that `LAYERS` is supposed to cover. */
export function authoredServerModules(): string[] {
	return readdirSync(SERVER)
		.filter((f) => f.endsWith('.ts') && !f.endsWith('.d.ts') && !GENERATED.has(f))
		.map((f) => f.replace(/\.ts$/, ''))
		.sort();
}
