// MOVED — do not edit this file.
//
// The classroom metrics implementation (LessonStat, LessonEvent, LessonStats)
// now lives in server/resources.ts, alongside the landing analytics it is
// modelled on. This was the staging copy used to draft it; it is kept only so a
// link to it does not 404, and it WILL drift if anyone edits it here.
//
// Tests: tests/integration/lesson-metrics.test.ts
