// GENERATED by scripts/build-pages.mjs — DO NOT EDIT.
// URL path -> YYYY-MM-DD that page's source last changed, for /sitemap.xml.
// A path is ABSENT when no honest date could be determined; the sitemap then
// omits <lastmod> for it rather than inventing one.
export const pageLastmod: Record<string, string> = {
	"/": "2026-08-19",
	"/privacy.html": "2026-08-18",
	"/age-rating.html": "2026-08-18",
	"/support.html": "2026-08-18",
	"/teachers": "2026-08-18",
	"/teachers/science": "2026-08-18",
	"/teachers/coding": "2026-08-18",
	"/learn": "2026-08-18",
	"/learn/web-development": "2026-08-18",
	"/developers/api": "2026-08-18",
	"/educator-guide.pdf": "2026-08-10",
	"/student-worksheets.pdf": "2026-08-09"
};
