// GENERATED by scripts/build-pages.mjs — DO NOT EDIT.
// Source of truth: scripts/site-pages.mjs. Regenerated by `npm run build:server`.

export type SitePage = {
	/** Pages that are the same page in another language share a group. */
	group: string;
	locale: string;
	path: string;
	/** Requests on the origin hostname are 301d to the apex. */
	redirect: boolean;
	sitemap: boolean;
};

export const SITE_ORIGIN = "https://wildwillows.app";
export const DEFAULT_LOCALE = "en";

/** Every public URL, keyed by the page key the endpoints ask for. */
export const PUBLIC_PAGES: Record<string, SitePage> = {
	"landing": {
		"group": "landing",
		"locale": "en",
		"path": "/",
		"redirect": true,
		"sitemap": true
	},
	"landing-es": {
		"group": "landing",
		"locale": "es",
		"path": "/es/",
		"redirect": true,
		"sitemap": true
	},
	"privacy": {
		"group": "privacy",
		"locale": "en",
		"path": "/privacy.html",
		"redirect": true,
		"sitemap": true
	},
	"age-rating": {
		"group": "age-rating",
		"locale": "en",
		"path": "/age-rating.html",
		"redirect": true,
		"sitemap": true
	},
	"support": {
		"group": "support",
		"locale": "en",
		"path": "/support.html",
		"redirect": true,
		"sitemap": true
	},
	"teachers": {
		"group": "teachers",
		"locale": "en",
		"path": "/teachers",
		"redirect": true,
		"sitemap": true
	},
	"teachers-science": {
		"group": "teachers-science",
		"locale": "en",
		"path": "/teachers/science",
		"redirect": true,
		"sitemap": true
	},
	"teachers-coding": {
		"group": "teachers-coding",
		"locale": "en",
		"path": "/teachers/coding",
		"redirect": true,
		"sitemap": true
	},
	"developers-api": {
		"group": "developers-api",
		"locale": "en",
		"path": "/developers/api",
		"redirect": true,
		"sitemap": true
	},
	"learn": {
		"group": "learn",
		"locale": "en",
		"path": "/learn",
		"redirect": true,
		"sitemap": true
	},
	"learn-code-builder": {
		"group": "learn-code-builder",
		"locale": "en",
		"path": "/learn/code-builder",
		"redirect": true,
		"sitemap": false
	},
	"learn-web-development": {
		"group": "learn-web-development",
		"locale": "en",
		"path": "/learn/web-development",
		"redirect": true,
		"sitemap": true
	},
	"educator-guide": {
		"group": "educator-guide",
		"locale": "en",
		"path": "/educator-guide.pdf",
		"redirect": false,
		"sitemap": true
	},
	"student-worksheets": {
		"group": "student-worksheets",
		"locale": "en",
		"path": "/student-worksheets.pdf",
		"redirect": false,
		"sitemap": true
	},
	"dashboard": {
		"group": "dashboard",
		"locale": "en",
		"path": "/dashboard",
		"redirect": false,
		"sitemap": false
	}
};

/**
 * group -> the locales it exists in. Only groups with a translation appear.
 * Feeds /sitemap.xml's xhtml:link alternates, which say the same thing the
 * pages’ own hreflang links do, from the same table, so they cannot disagree.
 */
export const PAGE_ALTERNATES: Record<string, { locale: string; path: string }[]> = {
	"landing": [
		{
			"locale": "en",
			"path": "/"
		},
		{
			"locale": "es",
			"path": "/es/"
		}
	]
};
