#!/usr/bin/env node
// Inlines public/*.html into server/pages.ts so the policy pages can be served
// by pure Harper ENDPOINTS — the hosted Harper serves no static files (the
// game UI ships only in the desktop app), but App Store Connect still needs
// public URLs for the privacy policy and age-suitability pages.
//
// Runs automatically as part of `npm run build:server` (before esbuild).
// server/pages.ts is generated + committed (like resources.js) so `npm run
// check`, Vite, and the integration harness all see a plain TS module and no
// bundler needs an .html loader. Edit public/*.html, not server/pages.ts.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const pages = {
	privacyHtml: 'public/privacy.html',
	ageRatingHtml: 'public/age-rating.html',
	supportHtml: 'public/support.html',
	dashboardHtml: 'public/dashboard.html',
	// Marketing landing page served at the site root (GET /). Self-contained:
	// screenshots are inlined as data URIs, so it ships as a single string like
	// the policy pages. Regenerate with scripts/build-landing.mjs when screenshots
	// or copy change.
	landingHtml: 'public/landing.html',
};

let out =
	'// GENERATED by scripts/build-pages.mjs — DO NOT EDIT.\n' +
	'// Source of truth: the files in public/. Regenerated by `npm run build:server`.\n\n';
for (const [name, path] of Object.entries(pages)) {
	const html = readFileSync(join(root, path), 'utf8');
	out += `/** Inlined from ${path} */\nexport const ${name}: string = ${JSON.stringify(html)};\n\n`;
}

// Social/OpenGraph preview image for the landing page, inlined as base64 so the
// endpoints-only Harper can serve it at GET /og-image.jpg (crawlers need a real
// fetchable URL — a data URI won't do for og:image).
const ogImageB64 = readFileSync(join(root, 'public/og-image.jpg')).toString('base64');
out += `/** Base64 of public/og-image.jpg — served by the og-image endpoint. */\nexport const ogImageB64: string = ${JSON.stringify(ogImageB64)};\n\n`;

// Unique stamp for THIS build, baked into the bundle and served by the
// GET /Version/ endpoint. deploy-coop.sh compares the served stamp against the
// staged bundle after deploying, so a node that silently kept the old
// component fails the deploy instead of quietly serving stale code.
const buildStamp = `${JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version}+${new Date().toISOString()}`;
out += `/** Stamp for this build (app version + build time) — see GET /Version/. */\nexport const buildStamp: string = ${JSON.stringify(buildStamp)};\n`;

writeFileSync(join(root, 'server/pages.ts'), out);
console.log(`server/pages.ts generated from ${Object.values(pages).join(', ')} (build ${buildStamp})`);

// The landing page's theme-song player (GET /theme.mp3) needs the audio served by
// the endpoints-only Harper, so we inline it as base64. It lives in its OWN module
// (not pages.ts) and is dynamic-imported by the Theme endpoint — that keeps this
// ~2 MB out of the web/desktop bundle (Vite code-splits it; it's never loaded in
// the game), while the server's esbuild build inlines it into resources.js.
const themeMp3B64 = readFileSync(join(root, 'public/theme.mp3')).toString('base64');
const themeOut =
	'// GENERATED by scripts/build-pages.mjs — DO NOT EDIT. Base64 of public/theme.mp3.\n' +
	`export const themeMp3B64: string = ${JSON.stringify(themeMp3B64)};\n`;
writeFileSync(join(root, 'server/theme-audio.ts'), themeOut);
console.log(
	`server/theme-audio.ts generated from public/theme.mp3 (${(themeMp3B64.length / 1024).toFixed(0)} KB base64)`,
);

// The landing page's "For teachers" section links two classroom PDFs (educator
// guide + student worksheets), served by GET /educator-guide.pdf and
// /student-worksheets.pdf. Same reasoning as the theme audio: the endpoints-only
// Harper serves no static files, so the bytes ride along as base64 in their OWN
// module, dynamic-imported by those endpoints — out of the web/desktop bundle,
// inlined into resources.js by the server build.
const pdfs = {
	educatorGuidePdfB64: 'public/pdfs/Wild Willows \u2014 Educator Guide.pdf',
	studentWorksheetsPdfB64: 'public/pdfs/Wild Willows \u2014 Student Worksheets.pdf',
};
let pdfOut =
	'// GENERATED by scripts/build-pages.mjs — DO NOT EDIT.\n' +
	'// Base64 of the classroom PDFs in public/pdfs/. Replace the PDFs and rebuild.\n';
for (const [name, path] of Object.entries(pdfs)) {
	const b64 = readFileSync(join(root, path)).toString('base64');
	pdfOut += `/** Inlined from ${path} */\nexport const ${name}: string = ${JSON.stringify(b64)};\n`;
	console.log(`server/pdf-assets.ts ← ${path} (${(b64.length / 1024).toFixed(0)} KB base64)`);
}
writeFileSync(join(root, 'server/pdf-assets.ts'), pdfOut);
