#!/usr/bin/env node
// Inlines public/*.html into server/pages.ts so the policy pages can be served
// by pure Harper ENDPOINTS — the hosted Harper serves no static files (the
// game UI ships only in the desktop app), but App Store Connect still needs
// public URLs for the privacy policy and age-suitability pages.
//
// Runs automatically as part of `npm run build:server` (before esbuild).
// server/pages.ts is generated + committed (like resources.js) so `npm run
// check`, Vite, and the integration harness all see a plain TS module and no
// bundler needs an .html loader. Edit public/*.html, not server/pages.ts.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const pages = {
	privacyHtml: 'public/privacy.html',
	ageRatingHtml: 'public/age-rating.html',
	supportHtml: 'public/support.html',
	dashboardHtml: 'public/dashboard.html',
};

let out =
	'// GENERATED by scripts/build-pages.mjs — DO NOT EDIT.\n' +
	'// Source of truth: the files in public/. Regenerated by `npm run build:server`.\n\n';
for (const [name, path] of Object.entries(pages)) {
	const html = readFileSync(join(root, path), 'utf8');
	out += `/** Inlined from ${path} */\nexport const ${name}: string = ${JSON.stringify(html)};\n\n`;
}

// Unique stamp for THIS build, baked into the bundle and served by the
// GET /Version/ endpoint. deploy-coop.sh compares the served stamp against the
// staged bundle after deploying, so a node that silently kept the old
// component fails the deploy instead of quietly serving stale code.
const buildStamp = `${JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version}+${new Date().toISOString()}`;
out += `/** Stamp for this build (app version + build time) — see GET /Version/. */\nexport const buildStamp: string = ${JSON.stringify(buildStamp)};\n`;

writeFileSync(join(root, 'server/pages.ts'), out);
console.log(`server/pages.ts generated from ${Object.values(pages).join(', ')} (build ${buildStamp})`);
