import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { installFakeIndexedDb, uninstallFakeIndexedDb, type FakeIdb } from '../helpers/fake-indexeddb';

// Two changes in this area can lose a world without failing anything else:
//
//  1. The save envelope's crypto was rewritten for speed (chunked base64, the
//     keystream prefix folded once instead of per block). A round-trip test
//     cannot catch a mistake there, because it encrypts AND decrypts with the
//     same new code — an algorithm that changed consistently still round-trips.
//     So the first block below imports a FIXTURE generated by the OLD code.
//  2. Browser saves moved from localStorage to IndexedDB, with a one-time
//     migration. jsdom has no IndexedDB, so without the shim in
//     tests/helpers/fake-indexeddb.ts none of that path runs in CI at all.

const LS_PREFIX = 'wild-willows:solo-save:';
const MIRROR_PREFIX = 'wild-willows:solo-save-pending:';
const store = new Map<string, string>();
(globalThis as any).localStorage = {
	getItem: (k: string) => store.get(k) ?? null,
	setItem: (k: string, v: string) => void store.set(k, v),
	removeItem: (k: string) => void store.delete(k),
	key: (i: number) => [...store.keys()][i] ?? null,
	get length() {
		return store.size;
	},
};

const h = vi.hoisted(() => ({ data: { Player: [] as any[] } as Record<string, any[]> }));
vi.mock('../../src/solo/backend', () => {
	const versions = new WeakMap<object, number>();
	let next = 1;
	const versionOf = (d: object) => {
		let v = versions.get(d);
		if (v === undefined) versions.set(d, (v = next++));
		return v;
	};
	return {
		serializeActiveSave: () => h.data,
		serializeActiveSaveJson: () => JSON.stringify(h.data),
		activeSaveRow: (t: string, id: string) => (h.data[t] || []).find((r: any) => r?.id === id) ?? null,
		activeSaveVersion: () => versionOf(h.data),
	};
});

const slotFile = (slotId: string, name: string, extra: Record<string, any> = {}) =>
	JSON.stringify({
		meta: { slotId, playerId: `${name}-x1`, name, appearance: { hat: 'straw' }, createdAt: 1, updatedAt: 2, ...extra },
		data: { Player: [{ id: `${name}-x1`, name }], TerrainTile: [{ id: 't1', area: 'meadow', x: 1, y: 1 }] },
	});

// Each scenario needs a module instance that has not yet opened a database,
// because saves.ts memoizes its handle for the life of the page.
async function loadSaves() {
	vi.resetModules();
	return await import('../../src/solo/saves');
}

describe('an exported save from before the crypto rewrite still imports', () => {
	beforeEach(() => {
		store.clear();
		uninstallFakeIndexedDb();
	});

	it('accepts a file produced by the previous implementation', async () => {
		const legacy = readFileSync('tests/fixtures/legacy-save.wildwillows.json', 'utf8');
		const { importSave, loadSaveData } = await loadSaves();

		const meta = await importSave(legacy);
		expect(meta.name).toBe('Willow');
		expect(meta.playerId).toBe('willow-a1b2c3');
		expect(meta.appearance.hat).toBe('straw');

		// and the WORLD came across, not just the label on it
		const file = await loadSaveData(meta.slotId);
		expect(file?.data.Player[0].unlockedBiomes).toEqual(['meadow', 'forest']);
		expect(file?.data.BiomeState[0].health).toBe(72);
		expect(file?.data.Placement[0].objectId).toBe('oak');
		expect(file?.data.Discovery[0].animalId).toBe('grasshopper');
	});

	it('still rejects a tampered legacy file', async () => {
		// The integrity tag has to keep working across the rewrite too, or the
		// refactor quietly turned a checked file into an unchecked one.
		const env = JSON.parse(readFileSync('tests/fixtures/legacy-save.wildwillows.json', 'utf8'));
		const { importSave } = await loadSaves();
		await expect(importSave(JSON.stringify({ ...env, enc: 'Zm9vYmFy' + env.enc.slice(8) }))).rejects.toThrow(
			'invalid-save',
		);
		await expect(importSave(JSON.stringify({ ...env, sig: 'deadbeefdeadbeefdeadbeefdeadbeef' }))).rejects.toThrow(
			'invalid-save',
		);
	});
});

describe('existing localStorage saves survive the move to IndexedDB', () => {
	let idb: FakeIdb;
	beforeEach(() => {
		store.clear();
		idb = installFakeIndexedDb();
	});
	afterEach(() => uninstallFakeIndexedDb());

	it('migrates a save byte-for-byte and frees the localStorage copy', async () => {
		const contents = slotFile('old-1', 'Ivy');
		store.set(LS_PREFIX + 'old-1', contents);

		const { listSaves, loadSaveData } = await loadSaves();
		expect((await listSaves()).map((m) => m.slotId)).toEqual(['old-1']);

		expect(idb.read('old-1')).toBe(contents); // exact, not merely equivalent
		expect(store.has(LS_PREFIX + 'old-1')).toBe(false); // this is what reclaims the quota
		expect((await loadSaveData('old-1'))?.meta.name).toBe('Ivy');
	});

	it('keeps the original when the migration write fails', async () => {
		uninstallFakeIndexedDb();
		installFakeIndexedDb({ failWrites: true });
		const contents = slotFile('old-2', 'Keep');
		store.set(LS_PREFIX + 'old-2', contents);

		const { listSaves, loadSaveData } = await loadSaves();
		expect((await listSaves()).map((m) => m.slotId)).toEqual(['old-2']);
		expect(store.get(LS_PREFIX + 'old-2')).toBe(contents); // untouched
		expect((await loadSaveData('old-2'))?.meta.name).toBe('Keep');
	});

	it('shows saves from BOTH stores when a migration was interrupted', async () => {
		// The tab closed part-way through, so some slots moved and some did not.
		// A load menu that showed only one store looks like the game ate half of
		// the player's saves.
		idb.seed('in-idb', slotFile('in-idb', 'Moved'));
		store.set(LS_PREFIX + 'in-local', slotFile('in-local', 'Pending'));

		const { listSaves } = await loadSaves();
		expect((await listSaves()).map((m) => m.slotId).sort()).toEqual(['in-idb', 'in-local']);
	});

	it('falls back to localStorage when IndexedDB will not open', async () => {
		uninstallFakeIndexedDb();
		installFakeIndexedDb({ openError: true });
		const { createSlot, listSaves } = await loadSaves();
		h.data = { Player: [{ id: 'sam-x1', name: 'Sam' }] };
		const slot = await createSlot({ playerId: 'sam-x1', name: 'Sam', appearance: {} });
		expect([...store.keys()]).toEqual([LS_PREFIX + slot.slotId]);
		expect((await listSaves()).map((m) => m.slotId)).toEqual([slot.slotId]);
	});

	it('does not hang when another tab is holding the database', async () => {
		uninstallFakeIndexedDb();
		installFakeIndexedDb({ blocked: true });
		store.set(LS_PREFIX + 'old-3', slotFile('old-3', 'Blocked'));
		const { listSaves } = await loadSaves();
		expect((await listSaves()).map((m) => m.slotId)).toEqual(['old-3']);
	});

	it('deleting a half-migrated save clears both stores, so it cannot come back', async () => {
		idb.seed('dup', slotFile('dup', 'Dup'));
		store.set(LS_PREFIX + 'dup', slotFile('dup', 'Dup'));
		const { deleteSave, listSaves } = await loadSaves();
		await deleteSave('dup');
		expect(await listSaves()).toHaveLength(0);
	});

	it('round-trips a new save through IndexedDB without touching localStorage', async () => {
		const { createSlot, loadSaveData } = await loadSaves();
		h.data = { Player: [{ id: 'new-x1', name: 'Fresh' }] };
		const slot = await createSlot({ playerId: 'new-x1', name: 'Fresh', appearance: {} });
		expect(store.size).toBe(0);
		expect(idb.slotIds()).toEqual([slot.slotId]);
		expect((await loadSaveData(slot.slotId))?.meta.name).toBe('Fresh');
	});
});

describe('the last save before the page closes is not lost', () => {
	// The regression this exists for: `beforeunload` did `void flushSoloSave()`,
	// which only ever worked because localStorage.setItem is SYNCHRONOUS — the
	// write completed inside the handler even though nothing awaited it. An
	// IndexedDB write started there is queued and thrown away with the page, so
	// the move to IndexedDB silently turned every close into lost progress.
	// The e2e suite caught it as "a restored area survives a reload".
	let idb: FakeIdb;
	beforeEach(() => {
		store.clear();
		idb = installFakeIndexedDb();
	});
	afterEach(() => uninstallFakeIndexedDb());

	it('carries the last moments of play across a reload', async () => {
		const first = await loadSaves();
		h.data = { Player: [{ id: 'pat-x1', name: 'Pat', unlockedBiomes: ['meadow'] }] };
		const slot = await first.createSlot({ playerId: 'pat-x1', name: 'Pat', appearance: {} });

		// The player unlocks the rest of the preserve, then closes the tab before
		// the throttled autosave has fired.
		h.data = {
			Player: [
				{ id: 'pat-x1', name: 'Pat', unlockedBiomes: ['meadow', 'forest', 'wetland', 'desert', 'alpine', 'coastal'] },
			],
		};
		first.persistOnUnload(slot);

		const reloaded = await loadSaves();
		const file = await reloaded.loadSaveData(slot.slotId);
		expect(file?.data.Player[0].unlockedBiomes).toHaveLength(6);
		// and the parked copy was folded in and cleared, not left to accumulate
		expect(store.has(MIRROR_PREFIX + slot.slotId)).toBe(false);
		expect(JSON.parse(idb.read(slot.slotId)!).data.Player[0].unlockedBiomes).toHaveLength(6);
	});

	it('reads a parked save that could not be folded in', async () => {
		uninstallFakeIndexedDb();
		installFakeIndexedDb({ failWrites: true });
		store.set(MIRROR_PREFIX + 'slot-9', slotFile('slot-9', 'Pending'));
		const { listSaves, loadSaveData } = await loadSaves();
		expect((await listSaves()).map((m) => m.slotId)).toEqual(['slot-9']);
		expect((await loadSaveData('slot-9'))?.meta.name).toBe('Pending');
	});

	it('prefers the parked copy over a staler one in IndexedDB', async () => {
		uninstallFakeIndexedDb();
		const stuck = installFakeIndexedDb({ failWrites: true });
		stuck.seed(
			'slot-3',
			JSON.stringify({
				meta: { slotId: 'slot-3', playerId: 'p3', name: 'Old', appearance: {}, createdAt: 1, updatedAt: 1 },
				data: { Player: [{ id: 'p3', gold: 1 }] },
			}),
		);
		store.set(
			MIRROR_PREFIX + 'slot-3',
			JSON.stringify({
				meta: { slotId: 'slot-3', playerId: 'p3', name: 'New', appearance: {}, createdAt: 1, updatedAt: 2 },
				data: { Player: [{ id: 'p3', gold: 99 }] },
			}),
		);
		const { loadSaveData } = await loadSaves();
		expect((await loadSaveData('slot-3'))?.data.Player[0].gold).toBe(99);
	});

	it('does not resurrect a deleted save from a parked copy', async () => {
		idb.seed('gone', slotFile('gone', 'Gone'));
		store.set(MIRROR_PREFIX + 'gone', slotFile('gone', 'Gone'));
		const { deleteSave, listSaves } = await loadSaves();
		await deleteSave('gone');
		expect(await listSaves()).toHaveLength(0);
	});

	it('leaves the desktop path alone — its writes never went through localStorage', async () => {
		(globalThis as any).wildWillowsDesktop = {
			isDesktop: true,
			saves: { list: async () => [], read: async () => null, write: async () => {}, remove: async () => {} },
		};
		try {
			const { persistOnUnload } = await loadSaves();
			persistOnUnload({ slotId: 's', playerId: 'p', name: 'D', appearance: {}, createdAt: 1, updatedAt: 1 });
			expect(store.size).toBe(0);
		} finally {
			delete (globalThis as any).wildWillowsDesktop;
		}
	});
});

describe('the load menu reads a save header without parsing the world', () => {
	beforeEach(() => {
		store.clear();
		uninstallFakeIndexedDb();
	});

	it('handles a caretaker name that looks like the file format', async () => {
		// listSaves slices the `meta` object off the front rather than parsing the
		// whole file. A name containing the delimiter would cut it in the wrong
		// place, and the save would vanish from the menu.
		for (const name of ['},"data":{"Player":[]}', '{{{{', '}}}}', 'back\\slash', 'quote"inside', '🌿 emoji']) {
			store.clear();
			store.set(LS_PREFIX + 's1', slotFile('s1', name));
			const { listSaves } = await loadSaves();
			const metas = await listSaves();
			expect(metas, `name ${JSON.stringify(name)} should still list`).toHaveLength(1);
			expect(metas[0].name).toBe(name);
		}
	});

	it('falls back to a full parse for a file whose meta is not first', async () => {
		const legacyShape = JSON.stringify({
			data: { Player: [] },
			meta: { slotId: 's2', playerId: 'p', name: 'Old', appearance: {}, createdAt: 1, updatedAt: 1 },
		});
		store.set(LS_PREFIX + 's2', legacyShape);
		const { listSaves } = await loadSaves();
		expect((await listSaves())[0].name).toBe('Old');
	});
});
